[tool.poetry]
name = "backupify"
version = "0.1.0"
description = ""
authors = ["Hugo Lundin <hugo@lundin.dev>"]

[tool.poetry.scripts]
backupify = "backupify.cli:backupify"

[tool.poetry.dependencies]
python = "^3.10"
spotipy = "^2.20.0"
click = "^8.1.3"
pyarrow = "^8.0.0"
python-dotenv = "^0.20.0"
halo = "^0.0.31"
pandas = "^1.4.3"
duckdb = "^0.4.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
